# Generated by Django 3.2.6 on 2021-09-28 09:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='product_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
    ]
