# Generated by Django 3.2.6 on 2021-09-28 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_review_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='date',
        ),
    ]
