# Generated by Django 3.2.6 on 2021-09-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_review_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='product_id',
            new_name='pname',
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
