# Generated by Django 3.2.6 on 2021-10-01 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_alter_review_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='date',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='date',
        ),
    ]
