# Generated by Django 3.2.6 on 2021-09-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_alter_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='username',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
