# Generated by Django 3.2.6 on 2021-09-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_testimonial_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='description',
            field=models.TextField(default='The site helped me achieve my goals'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='username',
            field=models.CharField(max_length=64),
        ),
    ]
