# Generated by Django 3.2.6 on 2021-09-25 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210919_1027'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
