# Generated by Django 3.2.6 on 2021-09-22 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='name',
            new_name='product_name',
        ),
    ]
