# Generated by Django 3.2.6 on 2021-09-22 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_name_review_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='product_name',
        ),
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
    ]
