# Generated by Django 3.2.6 on 2021-09-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210922_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='feedback',
            field=models.BooleanField(default=False),
        ),
    ]
