# Generated by Django 3.2.6 on 2021-09-26 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_review_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
